
server: 
 port: 8081 
 
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/artgallery?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1983
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      continue-on-error: false